Kingdorian/Contextproject-BeNine

- backend/src/main/java/com/benine/backend/ConfigReader.java
- backend/src/main/java/com/benine/backend/LogEvent.java
- backend/src/main/java/com/benine/backend/LogWriter.java
- backend/src/test/java/com/benine/backend/LogEventTest.java
- backend/src/test/java/com/benine/backend/LogWriterTest.java
It's a simple logger to log events that happen in the system. It writes the events to a file with a specified max size. If the file exceeds the limit it backs it up, clears it and starts over again. It keeps at most 1 backup.
> Created a simple logger that logs to a file

- backend/src/main/java/com/benine/backend/LogWriter.java
- cameramodule/src/test/java/com/benine/ipcameracontrol/IpcameraTest.java
Hotfix for the failing test of the max logsize (because of charset) on Bryan's (and possibly others) machine(s).
@bvanwijk
> Fix failing test (because of charset) and ipcamera hotfix

- .gitignore
- frontend/app.js
- frontend/modules/config.js
- frontend/modules/logger.js
- frontend/test/test_app.js
- frontend/test/test_config.js
- frontend/test/test_logger.js
I've added a config.json file, which is generated automatically on first start.
It's persistent over multiple requires, so you can just call require and use it in all modules.
I've also added this pattern to the logger, to make it as easy as possible to use these modules.
> NodeJS Configuration file + Refactor

- backend/src/main/java/com/benine/backend/LogWriter.java
- backend/src/main/java/com/benine/backend/Logger.java
- backend/src/main/java/com/benine/backend/Main.java
- backend/src/test/java/com/benine/backend/LoggerTest.java
- cameramodule/src/test/java/com/benine/ipcameracontrol/IpcameraTest.java
I enhanced the logger. Instead of the logwriter the logger should now be used to log. It logs to a specified log file and to the console. Both functions can be disabled and reenabled during program execution.
We'll first need to merge the hotfix pushed to master into develop before this can be merged into develop.
https://github.com/Kingdorian/Contextproject-BeNine/pull/28
> Enhancelogger

- frontend/app.js
- frontend/modules/config.js
- frontend/modules/logger.js
- frontend/test/test_config.js
Added a very simple API to NodeJS. You can now call /api/getserver to obtain a JSON object containing the server address and port.
> Frontend getserver api

- backend/pom.xml
Maven site was broken in my setup.
It appears this was related to checkstyle.xml.
Is anyone affected by the same problem and does this pr solve the problem?
> Fix maven-site malfunctioning

- backend/src/main/java/com/benine/backend/Main.java
I came across this bug which the test suite didn't catch.
Before anyone does a pull request. I suggest we are more careful with pull requests, because it seems reading code and running maven test is not always sufficient.
> Fix for wrong config path

- frontend/modules/config.js
- frontend/test/test_config.js
I've added a validator to the NodeJS config, so the program no longer crashes on an invalid configuration, but uses the default. Everything is logged in the log file.
This should fix #54
> Node config validator

- README.md
This provides the TA with information about where to find the generated reports.
> Add information about coverage tools and tests

- README.md
I added a link to the api docs to the readme so it can be found more easlily.
> Add reference to backend API

- backend/configs/main.conf
- backend/src/main/java/com/benine/backend/http/HttpController.java
- backend/src/test/java/com/benine/backend/CameraControlTest.java
- frontend/index.html
- frontend/public/css/style.css
- frontend/public/js/control.js
- frontend/public/js/generator.js
This should resolve the UI issues on develop.
> Develop ui fix

- frontend/public/css/style.css
I fixed the slider orientation, so large values are now back on top again.
> Fix slider orientation

- backend/src/main/java/com/benine/backend/database/MySQLDatabase.java
#78 
The presets are not removed anymore when the system starts.
> Fix presets removing

- frontend/index.html
- frontend/public/css/style.css
- frontend/public/js/generator.js
This is a very basic version of preset add and edit views.
Actual preset adding and editing functionality is missing here, since it is another sprint task.
> Preset View

- backend/src/main/java/com/benine/backend/Preset.java
- backend/src/test/java/com/benine/backend/PresetTest.java
I added preset keywords to the preset class.
> Preset keywords

- frontend/public/js/control.js
The joystick can now send commands to the backend at most once in 130 ms.
> Add timeout to joystick on move event.

- backend/src/main/java/com/benine/backend/Preset.java
- backend/src/main/java/com/benine/backend/database/MySQLDatabase.java
The few checkstyle and PMD warnings in develop are now  gone.
> Fix checkstyle and findbugs

- backend/src/main/java/com/benine/backend/LogEvent.java
- backend/src/main/java/com/benine/backend/Logger.java
- backend/src/test/java/com/benine/backend/LogEventTest.java
- backend/src/test/java/com/benine/backend/LoggerTest.java
As mentioned in https://github.com/Kingdorian/Contextproject-BeNine/issues/83 there is not much to tell about this really.
> Logger exception support

- backend/src/main/java/com/benine/backend/camera/IrisCamera.java
- backend/src/main/java/com/benine/backend/camera/ZoomingCamera.java
- backend/src/main/java/com/benine/backend/camera/ipcameracontrol/IPCamera.java
- backend/src/main/java/com/benine/backend/http/FocussingHandler.java
- backend/src/main/java/com/benine/backend/http/IrisHandler.java
- backend/src/test/java/com/benine/backend/camera/ipcameracontrol/IpcameraIrisTest.java
- backend/src/test/java/com/benine/backend/http/FocussingHandlerTest.java
- backend/src/test/java/com/benine/backend/http/IrisHandlerTest.java
- frontend/index.html
- frontend/public/js/control.js
As mentioned in https://github.com/Kingdorian/Contextproject-BeNine/issues/86. Currently the focus and iris sliders only zoom in or out, not with a certain speed. This will be fixed when fixing the maximum amount of api  calls and commands send to the camera are limited.
> Sliders acting as 1d joystick

- backend/configs/main.conf
- backend/src/main/java/com/benine/backend/http/PresetCreationHandler.java
- frontend/public/js/control.js
Fix for displaying the client view and creating a preset.
> Fix the currently not visible camera's and working UI

- backend/src/main/java/com/benine/backend/http/CameraInfoHandler.java
- backend/src/main/java/com/benine/backend/http/CreatePresetHandler.java
- backend/src/test/java/com/benine/backend/http/CreatePresetHandlerTest.java
- backend/src/test/java/com/benine/backend/http/PresetCreationHandlerTest.java
As I mentioned earlier, there are still some problems with the tests that I haven't been able to figure out. On develop the test coverage is high. Maybe you can point out some things that could be implemented better.
> Add the tags to the preset. 

- backend/database/databasefile.sql
- backend/src/main/java/com/benine/backend/ServerController.java
- backend/src/main/java/com/benine/backend/database/Database.java
- backend/src/main/java/com/benine/backend/database/MySQLDatabase.java
- backend/src/test/java/com/benine/backend/database/MySQLDatabaseTest.java
This makes it able to add, delete en get tags to/from the database.
I will create tests for this if the other branch is merged and i can merge from develop. I maked this pull request so you can review it already.
> Keywords in database

- frontend/index.html
- frontend/public/css/style.css
- frontend/public/js/control.js
- frontend/public/js/settings.js
We now have sliders in the settings window to adjust the sensitivity of the controls.
> Settings functions

- backend/src/main/java/com/benine/backend/PresetController.java
- backend/src/main/java/com/benine/backend/http/CameraInfoHandler.java
- backend/src/main/java/com/benine/backend/http/PresetsHandler.java
- backend/src/main/java/com/benine/backend/http/RemoveTagHandler.java
- backend/src/test/java/com/benine/backend/PresetControllerTest.java
- backend/src/test/java/com/benine/backend/http/PresetsHandlerTest.java
- backend/src/test/java/com/benine/backend/http/RemoveTagHandlerTest.java
Implemented deleting tags via the removetag endpoint.
> Delete tag endpoint

- backend/configs/main.conf
- backend/src/main/java/com/benine/backend/camera/SimpleCamera.java
- backend/src/main/java/com/benine/backend/camera/ipcameracontrol/IPCamera.java
- backend/src/main/java/com/benine/backend/http/CameraInfoHandler.java
- backend/src/main/java/com/benine/backend/http/SetCameraInUseHandler.java
- backend/src/test/java/com/benine/backend/camera/SimpleCameraTest.java
- backend/src/test/java/com/benine/backend/camera/ipcameracontrol/IpcameraTest.java
- backend/src/test/java/com/benine/backend/http/CameraFocusHandlerTest.java
- backend/src/test/java/com/benine/backend/http/SetCameraInUseHandlerTest.java
You can now get info about a camera's status (inuse:true|false) when getting the camera info also a camera can be set to in use or free throught the inuse endpoint.
> Camera in use http

- backend/configs/main.conf
- backend/database/databasefile.sql
- backend/resources/configs/maintest.conf
- backend/src/main/java/com/benine/backend/Preset.java
- backend/src/main/java/com/benine/backend/PresetController.java
- backend/src/main/java/com/benine/backend/ServerController.java
- backend/src/main/java/com/benine/backend/database/MySQLDatabase.java
- backend/src/main/java/com/benine/backend/http/CreatePresetHandler.java
- backend/src/test/java/com/benine/backend/PresetControllerTest.java
- backend/src/test/java/com/benine/backend/database/MySQLDatabaseTest.java
- backend/src/test/java/com/benine/backend/http/PresetsHandlerTest.java
- frontend/index.html
- frontend/public/js/presets.js
@bvanwijk and I fixed some bugs in the database, could you double check there are no errors anymore in the database? Otherwise I think this can be merged.
> Databasefix

- frontend/public/js/camera.js
- frontend/public/js/main.js
- frontend/public/js/preset.js
- frontend/public/js/presetcontroller.js
The server status is now again updated every 10 seconds.
The presets will be updated every 5 seconds.
> Refresh client

- backend/src/main/java/com/benine/backend/http/AutoPresetCreationHandler.java
- backend/src/main/java/com/benine/backend/http/PresetsHandler.java
- frontend/index.html
- frontend/public/js/control.js
Implemented the button as suggested in  #167. 
I cannot get the GLYPHICONS to work but for the rest this should now work for autocreating presets using the button in the interface (we also should look at the positioning of the button maybe @jochem725  can do this).
> Auto preset creation button

- backend/src/main/java/com/benine/backend/database/MySQLDatabase.java
- backend/src/test/java/com/benine/backend/database/MySQLDatabaseTest.java
This fixes the problem with the failing test.
> Fix database not setting the right preset id

- backend/database/databasefile.sql
- backend/src/main/java/com/benine/backend/camera/PresetCamera.java
- backend/src/main/java/com/benine/backend/camera/SimpleCamera.java
- backend/src/main/java/com/benine/backend/camera/ipcameracontrol/IPCamera.java
- backend/src/main/java/com/benine/backend/database/MySQLDatabase.java
- backend/src/main/java/com/benine/backend/http/CreatePresetHandler.java
- backend/src/main/java/com/benine/backend/http/EditPresetHandler.java
- backend/src/main/java/com/benine/backend/preset/IPCameraPreset.java
- backend/src/main/java/com/benine/backend/preset/Preset.java
- backend/src/main/java/com/benine/backend/preset/SimplePreset.java
- backend/src/test/java/com/benine/backend/camera/ipcameracontrol/IpcameraTest.java
- backend/src/test/java/com/benine/backend/database/MySQLDatabaseTest.java
- backend/src/test/java/com/benine/backend/http/CreatePresetHandlerTest.java
- backend/src/test/java/com/benine/backend/http/EditPresetHandlerTest.java
- backend/src/test/java/com/benine/backend/http/PresetsHandlerTest.java
- backend/src/test/java/com/benine/backend/http/RecallPresetTest.java
- backend/src/test/java/com/benine/backend/preset/IPCameraPresetTest.java
- backend/src/test/java/com/benine/backend/preset/SimplePresetTest.java
I have the name to the preset objects. The database is also updated and the endpoint also add a name to the preset, as well als editing a name.
> Preset name backend

- frontend/public/js/editperformance.js
- frontend/public/js/main.js
- frontend/views/partials/modals/edit-performance.ejs
- frontend/views/partials/modules/controls-module.ejs
I have added searching for presets in the performance edit window
> Search box in the performance edit window

- backend/database/databasefile.sql
- backend/src/main/java/com/benine/backend/database/MySQLDatabase.java
- backend/src/main/java/com/benine/backend/http/presetqueue/PresetQueueHandler.java
Solves the issue with the presetQueue handlers and saving preset in the queue.
> Fix presetqueues

- backend/src/main/java/com/benine/backend/http/EditPresetHandler.java
- backend/src/main/java/com/benine/backend/preset/IPCameraPreset.java
- backend/src/main/java/com/benine/backend/preset/SimplePreset.java
- frontend/public/js/camera.js
- frontend/public/js/preset.js
- frontend/public/js/presetcontroller.js
- frontend/views/partials/modals/create-preset.ejs
- frontend/views/partials/modals/edit-preset.ejs
Preset Names are now showed in the UI.
You can edit them and add them during creation of a preset.
If a preset name is defined it will be shown below a preset in the preset area.
> Preset name ui

- frontend/public/css/style.css
- frontend/public/js/editperformance.js
- frontend/public/js/liveview.js
- frontend/public/js/performance.js
I've resolved some minor issues with the preset queue edit view.
> Preset queue fix

- frontend/public/css/style.css
- frontend/views/partials/modals/auto-presets.ejs
> Add progressbar to ui

- .gitignore
- backend/findbugs-exclude.xml
- backend/pom.xml
- backend/src/main/java/com/benine/backend/LogWriter.java
- backend/src/main/java/com/benine/backend/camera/ipcameracontrol/IPCamera.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/Coordinate.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/PresetPyramidCreator.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/SubView.java
- backend/src/test/java/com/benine/backend/camera/CameraBusyExceptionTest.java
- backend/src/test/java/com/benine/backend/camera/ipcameracontrol/IpcameraTest.java
- backend/src/test/java/com/benine/backend/http/AutoCreationSubViewsHandlerTest.java
- backend/src/test/java/com/benine/backend/http/AutoPresetCreationHandlerTest.java
- backend/src/test/java/com/benine/backend/http/AutoPresetHandlerTest.java
- backend/src/test/java/com/benine/backend/http/CameraInfoHandlerTest.java
- backend/src/test/java/com/benine/backend/http/PresetDeletionHandlerTest.java
- backend/src/test/java/com/benine/backend/http/SetCameraInUseHandlerTest.java
- backend/src/test/java/com/benine/backend/http/presetqueueHandler/EditPresetQueueHandlerTest.java
- backend/src/test/java/com/benine/backend/preset/PresetTest.java
- backend/src/test/java/com/benine/backend/preset/autopresetcreation/AutoPresetCreatorTest.java
- backend/src/test/java/com/benine/backend/preset/autopresetcreation/CoordinateTest.java
- backend/src/test/java/com/benine/backend/preset/autopresetcreation/PresetPyramidCreatorTest.java
- backend/src/test/java/com/benine/backend/preset/autopresetcreation/SubViewTest.java
I fixed some small checkstyle and findbugs warnings.
> Cleanup warnings

- frontend/public/css/style.css
- frontend/views/partials/modules/presets-module.ejs
I've fixed the scrolling of the preset area, the search bar does no longer scroll with the content.
> Preset Search Scroll Fix

- backend/configs/main.conf
- backend/resources/configs/maintest.conf
- backend/src/main/java/com/benine/backend/http/AutoPresetCreationHandler.java
- backend/src/main/java/com/benine/backend/http/CameraZoomHandler.java
- backend/src/main/java/com/benine/backend/http/CreatePresetHandler.java
- backend/src/main/java/com/benine/backend/http/EditPresetHandler.java
- backend/src/main/java/com/benine/backend/http/RecallPresetHandler.java
- backend/src/main/java/com/benine/backend/preset/IPCameraPreset.java
- backend/src/main/java/com/benine/backend/preset/Preset.java
- backend/src/main/java/com/benine/backend/preset/PresetController.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/AutoPresetCreator.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/PresetPyramidCreator.java
- backend/src/main/java/com/benine/backend/video/StreamReader.java
- backend/src/test/java/com/benine/backend/http/CameraZoomHandlerTest.java
- backend/src/test/java/com/benine/backend/http/CreatePresetHandlerTest.java
- backend/src/test/java/com/benine/backend/http/EditPresetHandlerTest.java
- backend/src/test/java/com/benine/backend/http/RecallPresetTest.java
- backend/src/test/java/com/benine/backend/http/presetqueueHandler/DeletePresetFromPresetQueueHandlerTest.java
- backend/src/test/java/com/benine/backend/preset/PresetTest.java
Preset images are now created at one place in the code.
When a preset is removed from the system, the image will also be removed.
> Image creation

- frontend/public/js/presetcontroller.js
This adds a new tag to the top of the taglist, not on the bottom.
> Add new tag to front of list of tags

- backend/src/main/java/com/benine/backend/preset/PresetController.java
- backend/src/test/java/com/benine/backend/database/DatabaseControllerTest.java
- backend/src/test/java/com/benine/backend/preset/PresetControllerTest.java
- frontend/public/css/style.css
- frontend/public/js/presetcontroller.js
- frontend/views/partials/modals/create-preset.ejs
- frontend/views/partials/modals/edit-preset.ejs
- frontend/views/partials/modules/presets-module.ejs
Duplicate tags could not be added in the UI anymore.
If also limited the amount of characters for names and tags.
When a tag doesn't have a name the name: preset ID is set for this preset.
>  Duplicate tags

- backend/src/main/java/com/benine/backend/http/AutoPresetHandler.java
- backend/src/test/java/com/benine/backend/http/AutoPresetHandlerTest.java
Fix for the issue https://github.com/Kingdorian/Contextproject-BeNine/issues/222.
> Add validating params autopresetcreation

- backend/src/main/java/com/benine/backend/database/MySQLDatabase.java
- backend/src/test/java/com/benine/backend/database/MySQLDatabaseTest.java
The code in the database class is now changed to handle with the new database.
It doesn't work properly yet, first #227 and this need to be merged in database-sprint-8, then we can test if the functionality is correct.
> Database code change

- frontend/public/css/style.css
- frontend/public/js/autopresets.js
- frontend/public/js/main.js
- frontend/views/partials/modals/auto-presets.ejs
- frontend/views/partials/modals/settings.ejs
- frontend/views/partials/modules/controls-module.ejs
There are now input fields for tweaking the amount of rows,  columns and levels for the auto creation process.
> auto preset creation input for tweaking

- frontend/public/js/main.js
- frontend/views/partials/modules/controls-module.ejs
> Disable auto presetcreation when no camera is selected

- frontend/public/css/style.css
- frontend/public/js/settings.js
- frontend/views/partials/modals/settings.ejs
Start settings with 1 and increate size of sliders
> settings view

- backend/src/main/java/com/benine/backend/preset/autopresetcreation/Coordinate.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/PresetPyramidCreator.java
- backend/src/test/java/com/benine/backend/http/AutoCreationSubViewsHandlerTest.java
- backend/src/test/java/com/benine/backend/preset/autopresetcreation/PresetPyramidCreatorTest.java
The generation of the subviews now accounts for the aspect ratio of the camera. It will always try to fit the largest possible subview (with the correct aspect ratio).
> Aspectratio auto preset subviews

- backend/src/main/java/com/benine/backend/camera/SimpleCamera.java
- backend/src/main/java/com/benine/backend/camera/ipcameracontrol/FocusValue.java
- backend/src/main/java/com/benine/backend/camera/ipcameracontrol/IPCamera.java
- backend/src/main/java/com/benine/backend/camera/ipcameracontrol/IrisValue.java
- backend/src/main/java/com/benine/backend/database/MySQLDatabase.java
- backend/src/main/java/com/benine/backend/http/CameraMovingHandler.java
- backend/src/main/java/com/benine/backend/preset/IPCameraPreset.java
- backend/src/main/java/com/benine/backend/preset/Preset.java
- backend/src/main/java/com/benine/backend/preset/SimplePreset.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/AutoPresetCreator.java
- backend/src/test/java/com/benine/backend/camera/ipcameracontrol/FocusValueTest.java
- backend/src/test/java/com/benine/backend/camera/ipcameracontrol/IpcameraTest.java
- backend/src/test/java/com/benine/backend/camera/ipcameracontrol/IrisValueTest.java
- backend/src/test/java/com/benine/backend/database/MySQLDatabaseTest.java
- backend/src/test/java/com/benine/backend/http/CreatePresetHandlerTest.java
- backend/src/test/java/com/benine/backend/http/EditPresetHandlerTest.java
- backend/src/test/java/com/benine/backend/http/PresetDeletionHandlerTest.java
- backend/src/test/java/com/benine/backend/http/PresetsHandlerTest.java
- backend/src/test/java/com/benine/backend/preset/IPCameraPresetTest.java
- backend/src/test/java/com/benine/backend/preset/SimplePresetTest.java
- frontend/public/js/camera.js
- frontend/public/js/main.js
I have reduced the amount of parameters of some methods as suggested by the bettercodehub tool from SIG.
> Small unit interfaces

- frontend/public/js/preset.js
When the preset image is changed or added later, the image will be loaded in the UI.
> Update also the image when refreshing presets

- backend/src/main/java/com/benine/backend/http/CameraStreamHandler.java
- frontend/public/js/autopresets.js
I think this might fix the streams getting stuck.
Since the logger does not like asynchronous writing, we might want to consider disabling logging http requests to prevent a high amount of exceptions from occurring, or catch them without writing to the logger.
> Fix Stream getting stuck.

- backend/src/main/java/com/benine/backend/LogWriter.java
Fixes https://github.com/Kingdorian/Contextproject-BeNine/issues/206 I cannot replicate the behaviour described in the issue with this fix, can someone confirm this?
> Add semaphore for flushing

- frontend/public/js/camera.js
The focus and iris controls are now loaded correctly
> Load the focus and iris controls

- backend/database/databasefile.sql
- backend/src/main/java/com/benine/backend/database/MySQLDatabase.java
The database did not add the IPCameraPresets to the database, this is fixed now.
> Fix adding IPpresets to database

- frontend/public/css/style.css
- frontend/public/js/editperformance.js
- frontend/public/js/presetcontroller.js
- frontend/views/partials/modals/edit-tags.ejs
- frontend/views/partials/modules/controls-module.ejs
I've upgraded the tag window styling to match the edit performance window.
Please verify if tags are still added correctly. Editing a tag name is not functioning, maybe @egedebruin can take a look at this.
> Tag Window CSS

- backend/configs/main.conf
- backend/src/main/java/com/benine/backend/http/AutoPresetCreationHandler.java
- backend/src/main/java/com/benine/backend/http/AutoPresetCreationStatusHandler.java
- backend/src/main/java/com/benine/backend/http/PresetsHandler.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/AutoPresetCreator.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/PresetPyramidCreator.java
- backend/src/test/java/com/benine/backend/http/AutoCreationStatusHandlerTest.java
- frontend/public/js/autopresets.js
- frontend/views/partials/modals/auto-presets.ejs
> Implement progressbar

- backend/src/main/java/com/benine/backend/database/Database.java
- backend/src/main/java/com/benine/backend/database/MySQLDatabase.java
- backend/src/test/java/com/benine/backend/database/MySQLDatabaseTest.java
The cameras will now certainly not be removed from the database and I removed an unused method.
> Deleting cameras fix

- frontend/public/js/autopresets.js
- frontend/public/js/editperformance.js
- frontend/public/js/generator.js
- frontend/public/js/liveview.js
- frontend/public/js/main.js
- frontend/public/js/performance.js
- frontend/public/js/preset.js
- frontend/public/js/presetcontroller.js
- frontend/public/js/touch.js
In the UI for every preset there is a tag "camera <id>", this makes it possible to search for presets on camera id.
I have also checked all the javascript code with jshint and let the UI only display presets which belong to an available camera.
> Camera tag

- backend/src/main/java/com/benine/backend/LogWriter.java
- backend/src/main/java/com/benine/backend/http/AutoPresetCreationHandler.java
- backend/src/main/java/com/benine/backend/http/AutoPresetCreationStatusHandler.java
- backend/src/main/java/com/benine/backend/preset/SimplePreset.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/AutoPresetCreator.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/PresetPyramidCreator.java
- backend/src/test/java/com/benine/backend/http/AutoCreationStatusHandlerTest.java
- frontend/public/js/autopresets.js
The canvas now shows the subviews in green when presets have been created for them.
> Implement show subviews created

- frontend/modules/api.js
- frontend/public/js/main.js
I think this provides a fix for issues with server status determination. It prevents the server from hanging.
> Fix wrong server status determination

- frontend/views/partials/modals/edit-performance.ejs
The performance ok button should now no longer create a preset.
> Performance Ok preset creation fix

- frontend/views/partials/modals/edit-tags.ejs
This fixed #257, I have removed the cancel button from the edit tag modal, because it was redundant.
> Remove cancel button

- frontend/public/js/main.js
The presets are loaded again in the performances
> Fix preset loading in performances

- frontend/public/css/style.css
- frontend/public/js/editperformance.js
I've fixed performance deletion and solved a css issue. Please confirm this is working.
> Fix performance deletion

- backend/src/main/java/com/benine/backend/camera/CameraController.java
- backend/src/main/java/com/benine/backend/performance/PresetQueue.java
- backend/src/main/java/com/benine/backend/preset/Preset.java
- backend/src/main/java/com/benine/backend/preset/PresetController.java
- backend/src/main/java/com/benine/backend/preset/SimplePreset.java
This PR adds some comments to the JSON method because these were missing/ the method was too long.
> Add comments to the toJSON method.

- frontend/public/js/camera.js
- frontend/public/js/control.js
The toggle buttons are now showing the right status of the iris and focus
> The focus and iris toggle are now showing the right status

- backend/configs/main.conf
- backend/src/main/java/com/benine/backend/http/AutoPresetCreationHandler.java
- backend/src/main/java/com/benine/backend/http/AutoPresetCreationStatusHandler.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/AutoPresetCreator.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/PresetPyramidCreator.java
- backend/src/test/java/com/benine/backend/preset/autopresetcreation/PresetPyramidCreatorTest.java
- frontend/public/css/style.css
- frontend/public/js/autopresets.js
- frontend/public/js/preset.js
- frontend/views/partials/modals/auto-presets.ejs
The auto preset creation modal now functions correctly.
> Fix modal autopresetcreation

- frontend/public/js/autopresets.js
Now the higher layer subviews are drawn on top of the lower layer subviews, also each layer is slightly more inset then the previous layer.
> Fix subview drawingorder

- README.md
- backend/configs/main.conf
- backend/pom.xml
- backend/startserver.cmd
- backend/startserver.sh
I increased the versionnumber in the pom.xml and install and startserver scripts, please verify this works correctly.
> Increase version number in pom and deployable

- backend/src/main/java/com/benine/backend/http/AutoPresetCreationStatusHandler.java
- backend/src/main/java/com/benine/backend/preset/autopresetcreation/PresetPyramidCreator.java
> Fix last checkstyle warnings
